### ISSUE TITLE
When will the 4-axis version appear?

### ISSUE THREAD

**Issue by anshilike** [mstrens/grbl_controller_esp32#8]
look forward to

**Comment by mstrens** [comment]
The version is available on github but currently it is in another branch (AA-Axis).
This version can be configured for 3 or 4 axis depending on your set up in the config.h file.

I did not make many tests. So it could be that there are some bugs.
If so, let me know and I will try to fix them.

Note: If you are using a STM32, you have to activate the option AA-AXIS too.
Furthermore, if you already had uploaded a 3 axis version on the STM32, you have to reset your GRBL parameters (because the old parameters are kept but 4 axis uses more parameters and there is a shift)

**Comment by anshilike** [comment]
I haven't found any problems with the simple test of esp32.
